---
- hosts: all
  user: root
  vars:
    firewall:
      - service: https
        permanent: true
        state: enabled
        immediate: yes
      - service: http
        permanent: true
        state: enabled
        immediate: yes

  tasks:
    - name: Install httpd package
      package:
        name: httpd
        state: installed

    - name: Start http service
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Open Firewall ports
      include_role:
        name: rhel-system-roles.firewall
